# cna-lab

==== Step 1: Test and Deploy Freelancer service

Freelancer service is written in SpringBoot. It has a controller file which defines all endpoints, has a service class that massages data once returned by repository interface. Repository interace declares a table in postgres that is based on entity object defined in model class. 

Test cases run locally and uses H2 in-memory embedded data for testing. 

Also, defined openshift objects in fabric8 directory. Fabricate makes it easy to deploy an app into Openshift.

Main controller file src/main/java/com/example/freelancer/controller folder

Service file src/main/java/com/example/freelancer/service folder

Repository (JPA) file src/main/java/com/example/freelancer/repository folder

Model file src/main/java/com/example/freelancer/model folder 

Test cases src/test/java/com/example/freelancer/ folder

Sample data to be uploaded in postgres when starting up the application src/main/resources/import.sql file

Openshift objects in src/main/fabric8 folder

To test application locally, run

----
$ cd freelancer
$ mvn clean package 
----

Deploy the code in Openshift

----
# create postgres database
$ oc new-app --template=postgresql-persistent \
			-e POSTGRESQL_USER=user1 \
			-e POSTGRESQL_PASSWORD=welcome1

# create secret containing credentials information
$ oc create secret generic postgre-conn-details \
    --from-literal=POSTGRES_USER=user1 \
    --from-literal=POSTGRES_PASSWORD=welcome1

# deploy freelancer application in Openshift (we use fabric8 to deploy, see the respective 
# yamls file in src/main/fabric8 folder
$ mvn fabric8:deploy -DskipTests

# bind the secret with the deploy
$ oc set env --from=secret/postgre-conn-details dc/freelancer

# Access application, first get the route 
$ oc get routes
$ curl freelancer-cna-lab.192.168.99.100.nip.io/freelancers
$ curl freelancer-cna-lab.192.168.99.100.nip.io/freelancers/1
----

==== Step 2: Test and Deploy Gateway Service

Gateway service is written in Thorntail. Main Rest file (which defines endpoints) are defined in rest package. An interface is defined in service package that models the api calls to be executed with the base url pointing to Freelancer application in Openshift. Model data (retrieved by api call to freelancer app) is defined in model package.

Main Rest files in src/main/java/com/example/gateway/rest/ folder

Model files in src/main/java/com/example/gateway/model folder

Service files in src/main/java/com/example/gateway/service folder

Openshift objects in src/main/fabric8 folder

Test cases in src/test/java/com/exampple/gateway/ folder

Deploy code in Openshift

----
# Import openjdk image if not available in Openshift
$ oc import-image registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift:latest --confirm

# Build a new build config
$ oc new-build --name gateway -i openjdk18-openshift:latest --binary=true

# compile the package
$ cd gateway
$ mvn package -DskipTests

# Create a new imagestream via running a build
$ oc start-build gateway --from-file=target/demo-thorntail.jar

# Deploy gateway application
# we have defined a configmap which holds the url of the freelancers application. check out all object in 
# src/main/fabric8 folder
$ mvn fabric8:build fabric8:deploy -DskipTests

# access your application
$ curl gateway-cna-lab.192.168.99.100.nip.io/gateway/freelancers
$ curl gateway-cna-lab.192.168.99.100.nip.io/gateway/freelancers/1
----
